# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_remove_category_f_typeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='types',
            new_name='category',
        ),
    ]
