# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20181205_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='types',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
