# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0005_auto_20181205_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_show',
        ),
    ]
